version: "1"
services:
  server:
    environment:
      TAG: booking-movie-compose
    build: .
    container_name: booking-movie-compose
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: booking_movie
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
      - ./booking-movie_5-12.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: