spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking_movie
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: cinemaapp114@gmail.com
    password: wqlncrnxzifxzriy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 310995540967-b9inrvsgfmsukraofttpjuhjs8dg2qbv.apps.googleusercontent.com
            clientSecret: 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
            redirect_uri: http://localhost:8080/oauth2/callback/google

jwt:
  secret_key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  auth_expiration: 259200000

server:
  port: 8080
  error:
    include-message: always

discord:
  token: MTE1Njg1Njg2NTYyNDQzMjcwMA.G1jMKr.cdJmTgMASZgcwiLcvGzY3I4fRxtD-45q55ieWs
  poster_channel: test
  image_channel: test
  avatar_channel: test
  base_avatar_male: https://cdn.discordapp.com/attachments/1168144426141499412/1168152800119750677/unnamed.jpg?ex=6550ba12&is=653e4512&hm=7a8ec66da34b0c82e527cacb9712531f092cfc309abd0edfb8264763b06b9a12&
  base_avatar_female: https://cdn.discordapp.com/attachments/1168144426141499412/1168152799855530004/unnamed_1.jpg?ex=6550ba12&is=653e4512&hm=572879fb64472925ea1322086ad95e9d6b2a68c74ccbc179e07715a3c6ff3213&

verify:
  url: http://localhost:3000
  verify_expiration: 300000

promotion:
  point: 10
  promo: 1000

pay:
  expiration: 900000

scheduler:
  clear_showtime: 300000
  wait_showtime: 30
