spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking_movie
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

server:
  port: 8080
  error:
    include-message: always