spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: mysql://z1c4botdht9ol63h:t4l6t8azcidkew10@ilzyz0heng1bygi8.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/v286le79mlqi6c1y
    username: z1c4botdht9ol63h
    password: t4l6t8azcidkew10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: cinemaapp114@gmail.com
    password: wqlncrnxzifxzriy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 310995540967-b9inrvsgfmsukraofttpjuhjs8dg2qbv.apps.googleusercontent.com
            clientSecret: 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
            redirect_uri: http://localhost:8080/oauth2/callback/google

jwt:
  secret_key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  auth_expiration: 259200000

server:
  port: 8080
  error:
    include-message: always

discord:
  token: MTE1Njg1Njg2NTYyNDQzMjcwMA.G1jMKr.cdJmTgMASZgcwiLcvGzY3I4fRxtD-45q55ieWs
  poster_channel: test
  image_channel: test

verify:
  url: http://localhost:3000
  verify_expiration: 300000



